#!/usr/bin/env python3
import os
import datetime
from time import sleep
sometime = datetime.datetime.now()
alarmtime = sometime.replace(hour=11,minute=54, second=0, microsecond=0)
while datetime.datetime.now() < alarmtime:
    print("waiting")
    sleep(1)


os.system("mplayer sound.wav")
